CREATE TABLE comments ( id integer primary key not null, ticket_id integer not null references ticket ( id ), datecreated datetime not null default ( datetime('now', 'localtime') ), user text not null, comment text not null );
CREATE TABLE contacts ( ticket_id integer not null, email text not null );
CREATE VIRTUAL TABLE search using fts3 ( title, text, tag, user );
CREATE TABLE statustrack ( id integer primary key not null, ticket_id integer not null references ticket ( id ), datecreated datetime not null default ( datetime('now', 'localtime') ), user text not null, status text not null );
CREATE TABLE tags ( ticket_id integer not null references ticket ( id ), tag text not null );
CREATE TABLE tagsdesc ( tag text not null primary key, description text, fgcolor text, bgcolor text );
CREATE TABLE tickets ( id integer primary key not null, title text not null, status integer not null default ( 0 ), priority integer not null default ( 3 ), datecreated datetime not null default ( datetime('now', 'localtime') ), datemodified datetime not null default ( datetime('now', 'localtime') ), dateclosed datetime, user text not null );
CREATE TABLE timetrack ( id integer primary key not null, ticket_id integer not null references ticket ( id ), datecreated datetime not null default ( datetime('now', 'localtime') ), user text not null, minutes integer not null );
CREATE INDEX idx_comments_ticket_id on comments ( ticket_id );
CREATE INDEX idx_contacts_ticket_id on contacts ( ticket_id );
CREATE INDEX idx_statustrack_ticket_id on statustrack ( ticket_id );
CREATE INDEX idx_tags_tag on tags ( tag );
CREATE INDEX idx_tags_ticket_id on tags ( ticket_id );
CREATE INDEX idx_tickets_datecreated on tickets ( datecreated desc );
CREATE INDEX idx_tickets_datemodified on tickets ( datemodified desc );
CREATE INDEX idx_tickets_priority on tickets ( priority desc );
CREATE INDEX idx_tickets_status on tickets ( status );
CREATE INDEX idx_timetrack_ticket_id on timetrack ( ticket_id );
