CREATE TABLE OWNER ( 
	TICKET INTEGER, 
	OWNER VARCHAR(100) 
);
CREATE TABLE TAG (
    TICKET INTEGER,
    TAG VARCHAR(100)
);
CREATE TABLE TICKET (
    ID INTEGER PRIMARY KEY,
    STATUS INTEGER(1),
    TYPE INTEGER(1),
    PRIO INTEGER(1),
    IDPARENT INTEGER,
    DATECREATED DATETIME,
    DATECLOSED DATETIME,
    DATEMODIFIED DATETIME,
    USER VARCHAR(50),
    TEXT BLOB
);
CREATE INDEX IDTICKET ON TICKET (ID);
